language: node_js

node_js:
  - "8"

services:
  - mongodb

before_install:
  - openssl aes-256-cbc -K $encrypted_93d614a3c578_key -iv $encrypted_93d614a3c578_iv
    -in test/xero/xero-int-test-privatekey.pem.enc -out test/xero/xero-int-test-privatekey.pem -d
  - export XERO_PRIVATE_KEY=$( cat test/xero/xero-int-test-privatekey.pem

install:
  - npm install

before_script:
  - sleep 10

script:
  - npm run build

env:
  global:
    - XERO_PRIVATE_KEY_PATH={__dirname}
    ## XERO_CONSUMER_KEY
    - secure: cb7s/nJybwk9BKLvqhDiz8dc5wKW9OVK71NXel1i2s+DiqMRMiIF4rxRlZb/tMf6Pc/4LY862DX6TlCJENYq0+c+cfgX22QREkfGS5V6SemuANO2srUUVTWj9XX84nSKhWm4J9G0XRicHz7sKGb+7pd+1S/ERnVyqfDUtEf3gwKiNvUbPGzqpPHTxwTeEWMLeyZOWtgNImA51/Przzkxzqv4IpKy73Rn0prZkNfzV+Nj0fT+gBq+Zyvm4qBWF3OFvH/gs/MvuwFcVAGv39shz5z+CJMonv+Fp0FUO1Z/2ZVleGliQEiXTz0JC0oxsSORyzF9rLCX3928FkAbY/n7z9IxDJ+m3e204+eQmI8pz8binNcjfon8FKa78i1L5zToVhCbfTUxnUujw9/NVtPGjF/CAwZGjrtD5aEXCNPr1CRUsnNBH0Oj8560SvPXsTXKjjgUfWk9gEPAclgT4XGh5WpSDXQzAg66FOdxd30AyWcpNrmOwnBL2AQzoJIyCjvGDfNdACiRtIYFNkkKKQ95ke/SJeiJQxv6lE6WY8l17BQCgPzjXtfnUg1t6kkL7VNkr8mFBX4ANIgdzbk3SB4ZRlNJvNjEvPVJ+4v65vgyhvl79TCyV2vGsrsr+8GYsDTn4WA/La9rfxwI8uc+IEgMUeMyy2r1bJpY8c7gqdP8ty8=
    ## XERO_CONSUMER_SECRET
    - secure: G8dQdxu5RAF5nxC4Dsx0paZLhDCiocejpEzd9tVHqUjE2fVLkJ7IPbB4LBNX6R+M37mm0caF4M7pG/oaVvPO5DjZmuxwqtUIrzFUMCrJktc6X55w+YUbKcosEtA36aP+DPV2aX6va10NO1lr4DNpscHFJ/v1RmUJX38hU7cTEyvDbbO/rCijprECZv4OmXFf4wdc9EMYYiTGx6HhitFIpLeU/GPao1sfkFzitw93QH+XErGPwFpHDgiCR/9hOhe5KS8htR0kN+qzNz483+i9yRAnW9thElYVoaYZand75VGRxGdo2hL5qo+Lr90l0DIuwbKzZWDezDOwWH5zyHQGOwe7IwVclmrxPWSdUx4PlLK5BpC3fTeQkxHmyjOI2UZO1rZR0O0nB40BG1pihlDBcIUQH7fwfZVcMK1obEaMRHbk64/74qylc/qPkiMvHv0g1kadcQdRID2ACoQ/vOZfXvoi+9Oxfy1ybI2zLlUUDEHAQSAxWd5cM7Eie1evVZx4vEzYFeekdUn/L1hKNtQmhuK1WyQ0dH45f9mFvOJu+0lGosoYHNHlXx3rQYv+2SUdFWY/8BPkZvbTXWjgQCSJfpj2H7hSCW7qUCpqlsrItn1xNQeHOYE4bPACtDouZhOoizxRNi7UCY2+nrjBzfoSNCi9eJEjSzWNFDngypgD+tE=

deploy:
  provider: npm
  email: "esoftware@equalexperts.com"
  tag: next
  api_key: $NPM_TOKEN
  skip_cleanup: true
