language: node_js

node_js:
  - "8"

services:
  - mongodb

before_install:
- openssl aes-256-cbc -K $encrypted_93d614a3c578_key -iv $encrypted_93d614a3c578_iv
  -in xero-int-test-privatekey.pem.enc -out xero-int-test-privatekey.pem -d

install:
  - npm install

before_script:
  - sleep 10

script:
  - npm run build

deploy:
  provider: npm
  email: "esoftware@equalexperts.com"
  tag: next
  api_key: $NPM_TOKEN
  skip_cleanup: true
